- presidio-analyzer/analyzer/analyzer_engine.py
- presidio-analyzer/tests/test_analyzer_engine.py
Bug fix for all_fields=True.
Currently: Calling presidio's API with all_fields=True and a Spacy entity (person, location) does not return an answer. SpacyRecognizer expects entities in order to filter the ones needs to be evaluated. 
New logic gathers entities from all recognizers, in case of all_fields=True and sends it to recognizers, in order not to change recognizer internal logic.
> Entities list for all fields true

- docs/install.md
Building the base images will fail with a non-specific error message if docker is configured with a low memory limit, e.g. 4GB.  This adds a note so that it is more obvious to end users what to do when getting that message.
> Document build failure due to lack of memory

- presidio-analyzer/analyzer/predefined_recognizers/uk_nhs_recognizer.py
Got an exception when processing data while using re2. 
```
File "\site-packages\analyzer\predefined_recognizers\uk_nhs_recognizer.py", line 26, in validate_result
val = int(c)
ValueError: invalid literal for int() with base 10: 'U'
```
This catches that error as obviously this is not expected, and hence not valid.
> Add catch for ValueError exception.

- pipelines/templates/build-test-publish.yaml
Build python deps has an extra tab and extra tag "s" which fail the build.
> Fix bug in build deps

- pipelines/templates/build-test-publish.yaml
This PR fixes ADO build agent running out of physical disc space during PR validation.
the fix is splitting the makefile commands to two jobs:
* local validations - goland build, golang unit tests, python lint and unit tests
* containers build and functional tests on local agent using docker network
> Fix build agents running out of disk space

- .github/workflows/stale.yml
Adding this github actions allows us to automatically mark issues and PRs as stale if there is no update on them for 30 days
> Adding 'Stale' github action

- .github/workflows/stale.yml
Changed the github actions for closing stales issues to 120 days (instead of 30)
> Stale to 120 days

- presidio-analyzer/presidio_analyzer/predefined_recognizers/us_bank_recognizer.py
otherwise bank and check get concatenated
#309
> Fix typo to recognize a key context word

- azure-pipelines.yml
- pipelines/templates/build-test-publish.yaml
- pipelines/templates/free-agent-disk.yaml
- pipelines/templates/golang-environment.yaml
This PR handles 2 issues:
1. Move to pipenv sync (instead of install) in PR validation stage
1. Install Go using Go Tool as this is the new practice 
https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/go?view=azure-devops&tabs=go-current#set-up-go
1. Add a ci task/template to free disk space in the agent (currently inactive)
> Use GoTool to install Go + pipenv sync

- docs/developing_recognizers.md
These links were broken because they were relative to the current docs directory vs absolute from the base of the project folder.
> Fix documentation links

- charts/presidio/values.yaml
The current `values.yaml` file has a duplicate `resources:` property that causes the helm deployment to fail.
```
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: presidio/templates/analyzer-deployment.yaml:29:30: executing "presidio/templates/analyzer-deployment.yaml" at <.Values.analyzer.container.resources.requests.memory>: nil pointer evaluating interface {}.memory
Error: 1 chart(s) linted, 1 chart(s) failed
```
> fix(helm):  Remove duplicate resources property

- docs/tutorial_analyzer.md
- presidio-analyzer/conf/spacy_multilingual.yaml
- presidio-analyzer/presidio_analyzer/app.py
- presidio-analyzer/presidio_analyzer/predefined_recognizers/__init__.py
- presidio-analyzer/presidio_analyzer/predefined_recognizers/es_nif_recognizer.py
- presidio-analyzer/presidio_analyzer/predefined_recognizers/spacy_recognizer.py
- presidio-analyzer/presidio_analyzer/recognizer_registry/recognizer_registry.py
- presidio-analyzer/tests/test_analyzer_engine.py
- presidio-analyzer/tests/test_es_nif_recognizer.py
Using the recently added multi language support, this PR provides:
- Spanish national identification number recognizer
- Support for language parameter using GRPC script
- Examples using multilingual capabilities:
- Loading 2 different languages
- Querying with specific language
- Using python library or GRPC script with multiple languages
NOTE: In the future I expect to add more generic and Spanish recognizers
> analyzer - Spanish language

- presidio-analyzer/presidio_analyzer/predefined_recognizers/iban_recognizer.py
- presidio-analyzer/tests/test_iban_recognizer.py
The [IBAN pattern](https://github.com/microsoft/presidio/blob/master/presidio-analyzer/presidio_analyzer/predefined_recognizers/iban_recognizer.py#L32) detect possible IBAN codes with ` ` and `-` separators.
Sanitize theses characters from the matched text before validation to avoid #363
> Sanitize IBAN match before validation

- .pipelines/templates/functional-tests.yml
- azure-pipelines.yml
- docker-compose.yml
- functional-tests/common/methods.py
- functional-tests/tests/test_anonymizer.py
- presidio-anonymizer/Dockerfile
- presidio-anonymizer/app.py
Add additional job to CI pipeline for factional tests validation that:
1. Starts presidio cluster with docker-compose
2. Bootstraps the functional tests venv  
3. Runs the tests with pytest
> Run Functional Tests in CI

- azure-pipelines.yml
- presidio-analyzer/presidio_analyzer/entity_recognizer.py
- presidio-analyzer/presidio_analyzer/pattern.py
- presidio-analyzer/presidio_analyzer/pattern_recognizer.py
- presidio-analyzer/presidio_analyzer/recognizer_result.py
bug 2677
Replace class hints with strings, removed postponed annotations imports.
Reference: https://discuss.python.org/t/postponed-annotations-in-3-6/1885
> Remove future annotations to support python 3.6

- presidio-anonymizer/tests/integration/file_utils.py
- presidio-anonymizer/tests/integration/test_engine.py
- presidio-anonymizer/tests/resources/anonymize/mask_name_phone_number.in.json
- presidio-anonymizer/tests/resources/anonymize/mask_name_phone_number.out.json
- presidio-anonymizer/tests/resources/anonymize/mask_phone_number_with_bad_masking_char.in.json
- presidio-anonymizer/tests/resources/anonymize/mask_phone_number_with_bad_masking_char.out.json
This adds an infrastructure for anonymizer integration tests.
While 'integration' terminology was used before in the functional-tests context (where we test integration **between presidio services** through API), here, the integration is **between anonymizer components** (like engine-anonymizers, with as less mocks as possible).
Why is the functional-tests module not sufficient? Since presidio services can be used as packages, functionality can be extended without exposing new REST APIs.
In return, this additional test layer can reduce the coverage of the functional-tests module, to be mainly on the REST API, with simple and short happy scenarios and negative tests for the different http codes. 
Implementation-wise, each tested entry-point (method) will have a directory under …
> Anonymizer - Integration Tests Infra + Mask scenarios

- .pipelines/templates/build-containers.yml
- .pipelines/templates/release.yml
- docker-compose.yml
Add build and push step to release pipeline, with 'public/' as a prefix to the image name.
This will automatically push the container to MCR with a web-hook defined in our acr
*pushing 'latest' tag will be added in a different PR
> Push Presidio Containers to MCR

- presidio-analyzer/setup.py
- presidio-anonymizer/setup.py
setup.py's should not install_require flask as this is the non applicative way of using presidio
> Remove flask from presidio python packages

- .pipelines/templates/release-docs.yml
manually triggered pipeline to push docs into github pages
pipeline (not triggered yet in the main repo) - https://dev.azure.com/csedevil/Presidio/_build?definitionId=217
> release pipeline to push docs into github pages with mkdocs

- mkdocs.yml
Fix redirection to Redoc in Mkdoc.
This branch is currently deployed to GH pages and the fix seems to be working
> Redirect to Redoc with fqdn in mkdocs

- .pipelines/templates/release.yml
When running the release pipeline, and when the VERSION is the same, ignore GH release step failure to continue to the deployment
> Release Pipeline - continue on error for GH release

- .pipelines/templates/e2e-tests.yml
Fixing the condition for not starting compose cluster when running e2e against true environments.
Tested [here](https://dev.azure.com/csedevil/Presidio/_build/results?buildId=11332&view=logs&s=0b0143f5-1792-5cb0-42a5-36f61214a5e1&j=7d3b72a5-73cd-5eb7-6c36-be458b806191)
> Don't start cluster on e2e tests

- .pipelines/templates/e2e-tests.yml
- e2e-tests/pytest.ini
- e2e-tests/requirements.txt
- e2e-tests/tests/test_e2e_integration_flows.py
- presidio-analyzer/presidio_analyzer/recognizer_result.py
- presidio-analyzer/setup.py
- presidio-anonymizer/presidio_anonymizer/entities/recognizer_result.py
- presidio-anonymizer/setup.py
This PR introduces a simple "good day" scenario for integration of the analyzer and anonymizer packages.
In order to include the packages in the e2e project we had to do a workaround the config.py files, because in the venv context there is no VERSION file. The workaround introduces a fall back in case the VERSION file is not found. In this case we would use an environment variable, and the final fall back is for a default version which is considered pre-release so it wouldn't affect PyPI.
> added e2e package test

- docs/samples/deployments/spark/index.md
- docs/samples/deployments/spark/presidio_anonymize_blobs.py
This PR:
* Fixes the script to the API changes of anonymizer where the result text is at anonymized_results.text property.
* Adds a try-except clause for the udf function.
* Adds a note to the sample doc on the spark dependency version.
close #655
> Document dependencies for spark sample 

- docs/requirements-docs.txt
Latest version breaks docs release with:
`jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'toggle'`
> Lock mkdocs-material version

- docs/samples/deployments/spark/presidio_anonymize_blobs.py
This PR changes the implementation in the spark notebook to use presidio as broadcasted object instead of loading it in every UDF method which improves the performance of this sample greatly. this was previously not possible due to spacy limitations in serialization.
Other changes (AnonymizerConfig) reflect API changes to presidio since this sample was commited.
> Fix spark sample to run presidio in broadcast

- NOTICE
- presidio-image-redactor/Pipfile
- presidio-image-redactor/Pipfile.lock
- presidio-image-redactor/setup.py
For some reason, matplotlib 3.2.2 had some sort of dependency clash running on python 3.9.
Bumping it to the latest 3.6 supporting version seems to resolve this.
PR validation with the vii verification changes on the old version (issue reproduction):
https://dev.azure.com/csedevil/Presidio/_build/results?buildId=11948&view=results
PR validation with the vii verification changes on the new version:
https://dev.azure.com/csedevil/Presidio/_build/results?buildId=11951&view=results
> Bump matplotlib in image-redactor

- .pipelines/templates/release.yml
Publishing a GitHub release already tags the commit with the published version, so tagging step is readundent
> Remove git tag pipeline task

- docs/api-docs/api-docs.yml
- docs/supported_entities.md
- e2e-tests/tests/test_analyzer.py
- presidio-analyzer/presidio_analyzer/predefined_recognizers/__init__.py
- presidio-analyzer/presidio_analyzer/predefined_recognizers/medical_license_recognizer.py
- presidio-analyzer/presidio_analyzer/recognizer_registry/recognizer_registry.py
- presidio-analyzer/tests/test_certificate_number_recognizer.py
- presidio-analyzer/tests/test_recognizer_registry.py
Change the name of 'CertificateNumberRecognizer' to 'MedicalLicenseRecognizer'. 
Add it as a default predefined recognizer.
> Add Medical License as a Predefined Recognizer

- presidio-analyzer/Pipfile
- presidio-analyzer/Pipfile.lock
- presidio-analyzer/setup.py
- presidio-image-redactor/Pipfile
- presidio-image-redactor/setup.py
Update spacy to accommodate urllib version 1.26.5.
Implicitly have pydantic 1.7.4 version as dependency since Component Governance scan found version 1.8 to be effective through the setup.py, failing the build. 
Also added pydantic to pipenv to be aligned with pypi dependencies.
Another option is to reduce the Component Governance scan severity threshold in the build pipeline.
> Fix Versioning Issues

- presidio-analyzer/Dockerfile
- presidio-anonymizer/Dockerfile
- presidio-image-redactor/Dockerfile
This PR optimizes the Dockerfiles so that the final build image size is reduced. The big size is mostly caused by the `en_core_web_lg` package is being cached on `/root/.cache`. So by adding `ENV PIP_NO_CACHE_DIR=1`, the pip will not cache it anymore, reducing the image size.
I also merge some RUN commands into one RUN, so that it results to 1 layer instead of many layers.
```
BEFORE   AFTER
presidio-analyzer        2.1GB    1.26GB
presidio-anonymizer      212MB    196MB
presidio-image-redactor  2.34GB   1.46GB
```
> Optimize the Dockerfiles

- presidio-analyzer/presidio_analyzer/nlp_engine/nlp_artifacts.py
Adding the `nlp_engine` object to `NlpArtifacts`.
This is helpful when we need access to the original `nlp_engine` object.
One use case is we add a custom recognizer to use [`PhraseMatcher` from spaCy](https://spacy.io/api/phrasematcher). We can initialize the recognizer with the `PhraseMatcher` object, and use the `nlp` object to run the spaCy pipeline (with the matcher).
n/a
> Pass `nlp_engine` down to `NlpArtifacts`

- presidio-analyzer/presidio_analyzer/pattern_recognizer.py
- presidio-analyzer/tests/test_pattern_recognizer.py
When detecting pattern based recognizer using the `PatternRecognizer` class, the `AnalysisExplanation` object now holds the updated score after validation/invalidation
This PR fixes issue #847
> fixed analysis explanation having the wrong score after validation

- docs/tutorial/04_external_services.md
Fixed typo in the word 'wrapper'.
In the project documentation under:
`Step by step tutorial/External services/Calling a model in a different framework`
Changed word _wraper_ to _wrapper_.
This PR does not fix an open issue.
> Fixed typo in documentation

- presidio-anonymizer/presidio_anonymizer/core/text_replace_builder.py
- presidio-anonymizer/tests/test_anonymizer_engine.py
Fix the way we get the text for anonymization, get it from the original text and not from the anonymized one to make sure we are not overlapping with wrong text as in issue #888.
This PR fixes issue #888 
- [ X ] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [ X ] I have signed the CLA
- [ X ] My code includes unit tests
- [ X ] All unit tests and lint checks pass locally
- [ X ] My PR contains documentation updates / additions if required
> Fix getting the text before anonymizing

- docs/requirements-docs.txt
- mkdocs.yml
- overrides/main.html
Updates to the docs site:
1. Fixed missing reference to the new allow list tutorial on mkdocs.yml
2. Added a download button as jupyter notebooks are rendered as HTML
3. Updated requirements-docs.txt to use mkdoctsrings[python-legacy] as the mkdocstrings package no longer supports restructured-text ( https://github.com/mkdocstrings/python/issues/31 )
Example screenshot:
> bug fixes to mkdocs, added download button capability

- CHANGELOG.md
- docs/supported_entities.md
- presidio-analyzer/presidio_analyzer/predefined_recognizers/__init__.py
- presidio-analyzer/presidio_analyzer/predefined_recognizers/it_driver_license_recognizer.py
- presidio-analyzer/presidio_analyzer/predefined_recognizers/it_fiscal_code_recognizer.py
- presidio-analyzer/presidio_analyzer/recognizer_registry/recognizer_registry.py
- presidio-analyzer/tests/test_it_driver_license_recognizer.py
- presidio-analyzer/tests/test_it_fiscal_code_recognizer.py
This contribution adds two recognizers for Italian language:
- Fiscal code: similar to SSN used in United States
- Driver License: number of Italian driver license
For a brief introduction about Italian fiscal code: https://en.wikipedia.org/wiki/Italian_fiscal_code
> Italian fiscal code and driver license recognizers

- .pre-commit-config.yaml
This change fix issue with Black that prevent pre-commit script to work as expected.
This PR fixes issue #926
> bump black in pre-commit script to 22.3.0

- docs/samples/python/presidio_notebook.ipynb
Missing comma added.
For "I have signed the CLA" -- I don't know where that is. CONTRIBUTING doesn't make an allusion to it.
I understand I should update the changelog, but I'm hoping that since this is a change to what is essentially documentation, we can skip that?
I didn't open an issue for this, I went straight to a PR.
> Add missing comma in sample notebook

- presidio-analyzer/Pipfile
- presidio-analyzer/Pipfile.lock
- presidio-analyzer/setup.py
- presidio-cli/Pipfile
- presidio-cli/Pipfile.lock
- presidio-image-redactor/Pipfile
- presidio-image-redactor/Pipfile.lock
- presidio-image-redactor/setup.py
Bump some dependencies by re-locking pipenv
> Bump analyzer, image-redactor dependencies + Fix CLI hanging

- presidio-image-redactor/presidio_image_redactor/dicom_image_redactor_engine.py
- presidio-image-redactor/tests/test_dicom_image_redactor_engine.py
This Pull Request updates the logic for determining a DICOM pixel array's most common pixel value in defining the background color. The new logic now only focuses on large corner sections rather than the full image to more likely pick up on the pixel value most commonly associated with the background.
For more details, please see the issue this is referencing.
This PR fixes issue #971
> Updating DICOM redact box fill color selection

- CHANGELOG.md
- docs/image-redactor/evaluating_dicom_redaction.md
- presidio-image-redactor/Evaluation_Approach.md
- presidio-image-redactor/presidio_image_redactor/__init__.py
- presidio-image-redactor/presidio_image_redactor/bbox.py
- presidio-image-redactor/presidio_image_redactor/dicom_image_pii_verify_engine.py
- presidio-image-redactor/presidio_image_redactor/dicom_image_redactor_engine.py
- presidio-image-redactor/presidio_image_redactor/image_redactor_engine.py
- presidio-image-redactor/tests/integration/test_dicom_image_pii_verify_engine_integration.py
- presidio-image-redactor/tests/test_bbox.py
- presidio-image-redactor/tests/test_dicom_image_pii_verify_engine.py
- presidio-image-redactor/tests/test_dicom_image_redactor_engine.py
This PR moves existing bounding box code spread across different classes in the presidio-image-redactor module into one class. This new `BboxProcessor` class can also be used independently during evaluation, as specified in the updated documentation.
* Existing, general bounding box operations have been consolidated into `BboxProcessor`
* Existing tests for general bounding box operations have been moved into `presidio-image-redactor/tests/test_bbox.py` (no new tests have been added)
* `ImageRedactorEngine`, `DicomImageRedactorEngine`, and `DicomImagePiiVerifyEngine` and their tests have been updated to call bounding box operations from `BboxProcessor`
* Updated evaluation documentation to call bounding box operations from inherited `BboxProcessor` methods
This PR fixes issue #996
> Consolidating general bounding box operations

- presidio-image-redactor/presidio_image_redactor/dicom_image_redactor_engine.py
This PR fixes a minor typo where "photometric interpretation" is incorrectly referred to as "photometric interpolation", regarding DICOM images.
This PR fixes issue #1017
> Fixing typo (photometric interpolation -> photometric interpretation)

- presidio-image-redactor/presidio_image_redactor/dicom_image_redactor_engine.py
- presidio-image-redactor/tests/test_dicom_image_redactor_engine.py
This PR introduces a simple check to catch situations where users provide the wrong type of input into `DicomImageRedactorEngine.redact()`.
See issue #1015 as an example where the TypeError raise would have been helpful.
This PR fixes issue #1019
> Adding type check for image passed to DICOM redact

- presidio-image-redactor/presidio_image_redactor/dicom_image_pii_verify_engine.py
- presidio-image-redactor/tests/integration/resources/dicom_pii_verify_integration.json
- presidio-image-redactor/tests/integration/test_dicom_image_pii_verify_engine_integration.py
DICOM verify engine is not deterministic and removes duplicates based on list order. Prefer high-scored results when removing duplicates and use DICOM_METADATA to tag entities from the DICOM file metadata (currently overriding Spacy PERSON entities)
This PR fixes issue #1037
> Fix DICOM verify engine duplications

- CHANGELOG.md
- docs/anonymizer/index.md
- docs/samples/python/keep_entities.ipynb
- e2e-tests/tests/test_anonymizer.py
- presidio-anonymizer/presidio_anonymizer/operators/__init__.py
- presidio-anonymizer/presidio_anonymizer/operators/keep.py
- presidio-anonymizer/tests/operators/test_keep.py
- presidio-anonymizer/tests/operators/test_operators_factory.py
- presidio-anonymizer/tests/test_anonymizer_engine.py
This adds `keep` anonymizer. This is a no-op and doesn't modify the input string.
Having it allows us to keep track of all PII data in the anonymizer output, even when we want to preserve some types of PII.
I'm making a demo that highlights all PIIs and anonymizes only phone numbers.
When using `anonymizers: {"DEFAULT":{"type":"keep"}, "PHONE_NUMBER": {"type":"replace"}}`
> I'm John Smith and my phone is +1234567890
Becomes
> I'm `John Smith` and my phone is `<PHONE_NUMBER>`
> Added "keep" anonymizer

- mkdocs.yml
MyBinder allows you to run any jupyter notebook. mknotebooks has a feature for automatically creating mybinder urls, but it doesn't seem to work, so removing for now until we get this sorted out.
> removed binder link

- docs/analyzer/developing_recognizers.md
This PR contains a simple fix to broken hyperlink found in the docs. The old link points to `CONTRIBUTING.MD` and the fix points to `CONTRIBUTING.md`.
-
> FIX: Update broken hyperlink to CONTRIBUTING.md

- presidio-image-redactor/setup.py
`presidio-image-redactor` uses some fixed dependencies, such as pydantic==1.7.4. Changed to more flexible dependency versions
> hotfix for removing fixed dependency versions

- presidio-image-redactor/presidio_image_redactor/dicom_image_redactor_engine.py
The current version of the DICOM redactor only supports RGB and MONOCHROME images. This change enables the redactor to work with more photometric interpretations (e.g., YBR).
We also make one small change to safeguard against overwriting locally generated files via using a uuid rather than a hard-coded temporary file name string.
This PR fixes issue #967
> DICOM redactor improvement: Enabling more photometric interpretations

- presidio-anonymizer/presidio_anonymizer/entities/engine/operator_config.py
In `OperatorConfig` method `from_json` the docstring had wrong indentation for a closing brace. This commit fixes this.
I'm sorry to bother you with this tiny minor fix. Since presidio itself doesn't generate docs for `OperatorConfig` - it's not affected. The change is only useful when somebody else builds on top of persidio and references the `OperatorConfig`
> Fix Sphinx warning in OperatorConfig

- presidio-analyzer/presidio_analyzer/predefined_recognizers/spacy_recognizer.py
This PR fixes a type mismatch of the `check_label_groups` parameter in `SpacyRecognizer`. 
The [default value](https://github.com/microsoft/presidio/blob/67833d5be37ce2ce603836e120f40bb7513ee498/presidio-analyzer/presidio_analyzer/predefined_recognizers/spacy_recognizer.py#L40-L45) is of type `List[Tuple[Set, Set]]`, and the received parameter is of type `Tuple[Set, Set]`
> Fix type mismatch in check_label_groups parameter in SpacyRecognizer

- presidio-image-redactor/presidio_image_redactor/dicom_image_pii_verify_engine.py
- presidio-image-redactor/presidio_image_redactor/image_pii_verify_engine.py
- presidio-image-redactor/tests/test_dicom_image_pii_verify_engine.py
Updating both the standard and the DICOM image PII verification engines to allow use of ad-hoc recognizers and the allow list approach, as recently enabled with the redactor engines.
> Updating verification engines to include latest updates to redactor engines

- presidio-image-redactor/presidio_image_redactor/bbox.py
- presidio-image-redactor/tests/test_bbox.py
Making the bbox processor a little more robust to avoid common errors.
> Improve bbox processor

- presidio-anonymizer/presidio_anonymizer/batch_anonymizer_engine.py
The anonymize_list function of the BatchAnonymizerEngine class never returns List[EngineResult].
Changed the return type hint to List[Union[str, object]] and import
> anonymize_list return type hint fix

- presidio-image-redactor/presidio_image_redactor/dicom_image_pii_verify_engine.py
- presidio-image-redactor/presidio_image_redactor/image_analyzer_engine.py
- presidio-image-redactor/presidio_image_redactor/image_pii_verify_engine.py
- presidio-image-redactor/tests/integration/test_dicom_image_pii_verify_engine_integration.py
- presidio-image-redactor/tests/test_dicom_image_pii_verify_engine.py
- presidio-image-redactor/tests/test_image_analyzer_engine.py
Update verification engines to enable use of OCR custom parameters and ad-hoc recognizers like we have with the redactors. Also adding ability to plot a given set of bounding boxes to help visually inspect given bboxes.
> Updating verification engines and enable plotting of custom bboxes

- CHANGELOG.md
- NOTICE
- docs/image-redactor/index.md
- presidio-image-redactor/Pipfile
- presidio-image-redactor/presidio_image_redactor/__init__.py
- presidio-image-redactor/presidio_image_redactor/document_intelligence_ocr.py
- presidio-image-redactor/tests/conftest.py
- presidio-image-redactor/tests/engine_test_utils.py
- presidio-image-redactor/tests/integration/methods.py
- presidio-image-redactor/tests/integration/test_dicom_image_pii_verify_engine_integration.py
- presidio-image-redactor/tests/integration/test_dicom_image_redactor_engine_integration.py
- presidio-image-redactor/tests/integration/test_image_processing_engine.py
- presidio-image-redactor/tests/integration/test_image_redactor_engine.py
- presidio-image-redactor/tests/test_document_intelligence_ocr.py
Initial support for document intelligence
This PR fixes issue #1183
> Msft document intelligence ocr

- docs/analyzer/languages-config.yml
When using the provided [languages-config.yml](https://github.com/microsoft/presidio/blob/main/docs/analyzer/languages-config.yml) file from the documentation for multi-language support, I got the following error:
```
File "[...]/site-packages/presidio_analyzer/nlp_engine/ner_model_configuration.py", line 125, in from_dict
return cls(**nlp_engine_configuration)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: presidio_analyzer.nlp_engine.ner_model_configuration.NerModelConfiguration() argument after ** must be a mapping, not list
```
Changing the format in the YAML file fixes this.
Reproduction:
```
from presidio_analyzer.nlp_engine import NlpEngineProvider
provider = NlpEngineProvider(conf_file="languages-config.yml")
nlp_engine_eng_french = provider.create_engine()
```
- Fails with …
> Change ner_model_configuration from list to map in languages-config.yml example

- presidio-image-redactor/presidio_image_redactor/dicom_image_redactor_engine.py
In dicom_image_radactor_engine.py, the image intensity are rescaled using the function _rescale_dcm_pixel_array(). In the rescaling formula, changes are made to use the max and min intensity of the image, instead of assuming the smallest intensity is 0. 
This PR fixes issue #1227
> fixes bug #1227

- docs/analyzer/nlp_engines/spacy_stanza.md
The example was missing the super call in the constructor. Thus the example will fail as the super constructor initialized the ner config.
> Fix spacy_stanza.md example

- docs/samples/python/transformers_recognizer/index.md
Removed the extra symbol that causing error to load the site from transformers_recognizer documentation.
The earlier link was - https://huggingface.co/models?pipeline_tag=token-classification&sort=downloads> this link contains an extra symbol ">" that causing the error to load this link. Updated the link by removing that symbol now new link is this - https://huggingface.co/models?pipeline_tag=token-classification&sort=downloads. 
This PR fixes issue #1240
> Updated index.md of transformers_recognizer documentation

- presidio-anonymizer/presidio_anonymizer/batch_anonymizer_engine.py
Replace `object`  with `Any`. Mark the input list argument as being nullable. Document the existing behaviour in the docstring.
[This PR fixes issue #1249 
](https://github.com/microsoft/presidio/issues/1249)
- N/A My code includes unit tests
- N/A All unit tests and lint checks pass locally
- N/A My PR contains documentation updates / additions if required
> Update anonymize_list type hints and document that sometimes items will be ignored.

- presidio-anonymizer/presidio_anonymizer/operators/__init__.py
- presidio-anonymizer/presidio_anonymizer/operators/keep.py
- presidio-anonymizer/tests/integration/test_deanonymize_engine.py
- presidio-anonymizer/tests/operators/test_keep.py
- presidio-anonymizer/tests/operators/test_operators_factory.py
Implements the `keep` operator for deanonymisation too.
It keeps all the methods from the Keep class and extends only the ones that return the type.
Concrete classes MUST subclass `Operator` type, since operator discovery is done with `Operator.__subclasses__()`
This PR fixes issue #1254
> Add keep operator as deanonymizer

- presidio-analyzer/presidio_analyzer/nlp_engine/spacy_nlp_engine.py
Currently `SpacyNlpEngine` does not support use of local model paths. This is important for offline/airgapped environments where it is not possible to download spacy model on the fly
Follows Spacy's internal logic in `.load`
```py
if is_package(name):  # installed as package
465     return load_model_from_package(name, **kwargs)  # type: ignore[arg-type]
466 if Path(name).exists():  # path to model data directory
467     return load_model_from_path(Path(name), **kwargs)  # type: ignore[arg-type]
```
> Allow local Spacy Models to be loaded in NLP Engine

- CHANGELOG.md
- presidio-image-redactor/presidio_image_redactor/image_analyzer_engine.py
- presidio-image-redactor/tests/conftest.py
- presidio-image-redactor/tests/test_image_analyzer_engine.py
Changing the method redact from class ImageAnalyzerEngine to enable select others languages in addition "en".
Now is possible use other languages like "pt" and configure tesseract to use the wished language
This PR fixes issue #1274
- [ x ] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [ x ] I have signed the CLA (if required)
- [  x ] My code includes unit tests
- [ x ] All unit tests and lint checks pass locally
- [ x ] My PR contains documentation updates / additions if required
> Bugfix issue #1274

- README.MD
- presidio-analyzer/presidio_analyzer/nlp_engine/spacy_nlp_engine.py
Upgrade pip
```WARNING: You are using pip version 22.0.4; however, version 23.3.2 is available.```
> Upgrade pip

- presidio-analyzer/presidio_analyzer/predefined_recognizers/phone_recognizer.py
- presidio-analyzer/tests/test_phone_recognizer.py
Addition of `leniency` parameter in predefined `PhoneRecognizer`
-> The `PhoneRecognizer` failed to detect phone numbers when they appeared without any space between text and number, as seen in cases like `testdata630-596-1111`.
-> Internally, the `PhoneRecognizer` utilizes the [phonenumbers](https://github.com/daviddrysdale/python-phonenumbers) library for phone number detection. This library offers a parameter known as `leniency`, which determines the flexibility of the phone number format. The leniency parameter ranges from `0 to 3`, with higher values indicating more strict phone number format match.
-> Initially, the leniency factor in `PhoneRecognizer` was set to `1`, causing it to overlook phone numbers lacking spaces between text and digits. To address this issue, we've enhanced …
> Addition of leniency parameter in predefined PhoneRecognizer

- presidio-analyzer/presidio_analyzer/predefined_recognizers/us_bank_recognizer.py
Those two keywords in US_BANK_NUMBER wouldn't bump the entity's score because of Python multiline concatenation.
- Added a comma to prevent concatenation
- Move the keyword _below_ the comment to avoid such mistakes in the future
Additionally, I checked every other recognizer, but it didn't seem to occur elsewhere.
Here was my `grep` to look for it:
```
rg --multiline-dotall -U 'CONTEXT.*[^"]+"\n' presidio-analyzer/presidio_analyzer/predefined_recognizers/*.py
```
~~This PR fixes issue #XX~~ No issue made. The fix is so simple I didn't thing this was needed.
> Fix bug where "bank" and "check" wouldn't work for `US_BANK_NUMBER` recognizer

- CHANGELOG.md
- presidio-analyzer/presidio_analyzer/predefined_recognizers/phone_recognizer.py
- presidio-analyzer/tests/test_phone_recognizer.py
Changed how the recognizer parameter for the AnalysisExplanation is populated for the PhoneRecognizer so that it get's referenced correctly
This PR fixes issue [#1330 ](https://github.com/microsoft/presidio/issues/1330)
> Bugfix - Fix for incorrectly referenced recognizer in analysis_explanation using PhoneRecognizer

- presidio-analyzer/presidio_analyzer/pattern.py
- presidio-analyzer/presidio_analyzer/pattern_recognizer.py
This change caches the compiled regexes of `Pattern`s in `presidio-analyzer`.
A large portion of time is spent compiling the regex patterns when calling `/analyze` on the `presidio-analyzer`. For the following request:
```
curl -d '{"text":"Facere Konopelski alias animi dis
tinctio vel. Ratione corrupti quae consequuntur omnis eligendi. Excepturi et atque vol
uptas nemo reiciendis. Doloribus odio dolor http://www.nnrhwie.org/ ullam quibusdam. Q
ui sed 6011237658142640 fugiat labore et. Odio a explicabo ut maiores neque. Quidem ne
que magni 6011158690503127 qui sapiente. Necessitatibus est molestias Champlin vero vo
luptates. Tempore voluptate officiis quos error deleniti. Pariatur illum et est ipsum 
sed. Vitae voluptatem optio doloremque nulla repudiandae. Unde +6732345678 quo explica
bo …
```
> Cache compiled regexes in analyzer

- docs/structured/index.md
- presidio-structured/presidio_structured/analysis_builder.py
- presidio-structured/tests/conftest.py
- presidio-structured/tests/test_analysis_builder.py
I implemented an additional `selection_strategy` option in the `generate_analysis()` function, allowing users to define their preferred strategy for entity selection. Previously, the function only enabled selection based on the most common entity, which could result in scenarios where a small number of high-confidence entities were overshadowed by a larger number of low-confidence entities. Now, users have the flexibility to choose between three strategies: _most common_, _highest_confidence_ or _mixed_.
I would love to hear to hear feedback and suggestions!
This PR fixes issue #1316
> feat: Implement user-defined entity selection strategies in Presidio Structured

- presidio-analyzer/conf/transformers.yaml
- presidio-analyzer/presidio_analyzer/nlp_engine/ner_model_configuration.py
Changing the way transformers are aggregating entities from `simple` to `max`, as it has a slightly better recall on a test dataset.
This PR partially addresses issue #1262
> Changed default aggregation_strategy to max

- presidio-image-redactor/presidio_image_redactor/dicom_image_redactor_engine.py
- presidio-image-redactor/tests/integration/test_dicom_image_redactor_engine_integration.py
Metadata gathered from DICOM was not passed as an ad-hoc deny-list due to a bug in the code
This PR fixes issue #1309
> Fixed wrong condition for dicom metadata

- docs/installation.md
The ports on the samples on this page (https://microsoft.github.io/presidio/samples/docker/) and the postman collection do not align with the documentation found here. This PR is to align it.
Updated port references to match documentation and postman collections.
> Align Docker ports with documentation and postman collection.

- .pipelines/templates/release.yml
We no longer have permissions to release the cli package, dropping it from the release pipeline
> Do not release presidio-cli as part of the release pipeline

- presidio-analyzer/presidio_analyzer/recognizer_registry/recognizers_loader_utils.py
When configuration is loaded, the current version of the code only does an `open` call which leaves a dangling file reference that is never closed. While this isn't a major issue, we found that in the project where we use presidio, this causes pytest to issue warnings about unclosed resources (that for us is set up to be converted into test errors).
I'm not sure why, but this happens only with version `2.2.354` but not `2.2.353`.
Didn't create an issue as just contributing a fix was faster for me.
> Make sure that configuration files are closed when loading them

- docs/samples/docker/litellm.md
- docs/samples/index.md
- mkdocs.yml
Adds a sample doc for setting up Presidio (docker image) with LiteLLM Proxy for implementing PII Masking across 100+ LLMs. 
n/a 
cc: @omri374 @SharonHart
> (docs) Use Presidio across Anthropic, Bedrock, VertexAI, Azure OpenAI, etc. w/ LiteLLM Proxy

- .pipelines/templates/build-and-push-containers.yml
- .pipelines/templates/e2e-tests.yml
- .pipelines/templates/test-docs.yml
- azure-pipelines-ci.yml
- azure-pipelines.yml
Updating `projectName` on DockerCompose task due to CI issues:
```bash
##[warning]The project name "microsoft/presidio" must be a valid docker compose project name. Follow the link for more details: https://aka.ms/azdo-docker-compose-v1
##[error]invalid project name "microsoft/presidio": must consist only of lowercase alphanumeric characters, hyphens, and underscores as well as start with a letter or number
##[error]The process '/usr/bin/docker' failed with exit code 15
```
@SharonHart @RoeyBC merging this to unblock the CI, but please review. Thanks!
> Update CI due to DockerCompose project name issue

- presidio-analyzer/presidio_analyzer/predefined_recognizers/phone_recognizer.py
- presidio-analyzer/tests/__init__.py
- presidio-analyzer/tests/assertions.py
- presidio-analyzer/tests/test_phone_recognizer.py
Hi, long time user but first time contributing. Happy to learn & correct if something required. This is a minor change that a bug that I reported. The currently used **phonenumbers.PhoneNumberMatcher** function doesn't handle phone number starting with country code, the fucntion docstring (below) says to use different "region" parameter for such phone numbers.   
``` 
country -- The country to assume for phone numbers not written in
international format (with a leading plus, or with the
international dialing prefix of the specified region). May be
None or "ZZ" if only numbers with a leading plus should be
considered.
```
Added code handles such phone number separately & resolves the mentioned bug.
This PR fixes issue https://github.com/microsoft/presidio/issues/1425
> added logic to handle phonenumbers with country code

- presidio-analyzer/tests/test_analyzer_engine.py
- presidio-analyzer/tests/test_nlp_engine_provider.py
- presidio-analyzer/tests/test_recognizer_registry.py
- presidio-analyzer/tests/test_stanza_recognizer.py
- presidio-analyzer/tests/test_transformers_recognizer.py
Reduce memory usage of Presidio Analyzer test suite (excluding Azure AI language recognizer tests) down to ~6GB from ~8GB. When run locally the tests runtime went from ~60 seconds to ~25 seconds.
- Removed duplicate `nlp.load` call on each iteration of Stanza and transformers recognizer tests.
- Paramatized `test_when_analyze_with_unsupported_language_must_match` tests to avoid calling `AnalyzerEngine` five times in single test
- Mocked nlp engine in `test_when_analyze_with_unsupported_language_must_match` as test doesn't require nlp model to be loaded
- Removed unused fixtures - [pytest-unused-fixtures](https://github.com/mikicz/pytest-unused-fixtures) plugin used to detect them
This PR fixes issue #1427
> Reduce memory usage of Analyzer test suite

- presidio-analyzer/presidio_analyzer/batch_analyzer_engine.py
- presidio-analyzer/presidio_analyzer/nlp_engine/nlp_engine.py
- presidio-analyzer/presidio_analyzer/nlp_engine/spacy_nlp_engine.py
- presidio-analyzer/tests/test_batch_analyzer_engine.py
> added batching support

- presidio-analyzer/presidio_analyzer/nlp_engine/spacy_nlp_engine.py
- presidio-analyzer/tests/test_spacy_nlp_engine.py
A small fix which makes sure that ignored labels (in ner_model_configuration) are not part of the supported entities when calling `get_supported_entities`
> Remove ignored labels from supported entities

- presidio-analyzer/presidio_analyzer/predefined_recognizers/us_ssn_recognizer.py
- presidio-analyzer/tests/data/context_sentences_tests.txt
- presidio-analyzer/tests/test_context_support.py
As discussed in #1452, two of the CONTEXT words ("ssn#" and "ss#")  in UsSsnRecognizer() did not work correctly since # is tokenized.
The US_SSN tests in context_sentences_tests.txt were also updated.  078051120 is [invalidated](https://github.com/microsoft/presidio/blob/c54ce2b9cf8795a168711a9fc6954d47d3269683/presidio-analyzer/presidio_analyzer/predefined_recognizers/us_ssn_recognizer.py#L76) so most of these tests were not doing anything.  The correct place to check valid/invalid numbers is in [test_us_ssn_recognizer](https://github.com/microsoft/presidio/blob/c54ce2b9cf8795a168711a9fc6954d47d3269683/presidio-analyzer/tests/test_us_ssn_recognizer.py#L17)
Prior to this change if the text was "My ssn# is xxx-xx-xxxx" then "ssn" instead of "ssn#" would have been used for a context match. …
> Update US_SSN CONTEXT and unit test

- docs/analyzer/nlp_engines/transformers.md
- presidio-analyzer/presidio_analyzer/conf/transformers.yaml
updated the docs for a transformers based pipeline, to make it clearer, and added an example for configuration through code. Based on the discussion in #1463 
Also changed the default config in the docs to match the one in the code.
> Updates to the transformers conf docs and yaml file

- docs/community.md
This change allows presidio users to integrate with HashiCorp Vault using a [python library](https://github.com/sahajsoft/presidio-vault).
N/A
- [x ] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [x ] My PR contains documentation updates / additions if required
> Add a link to HashiCorp vault operator resource

- .pipelines/templates/e2e-tests.yml
- .pipelines/templates/lint-build-test.yml
- .pipelines/templates/test-docs.yml
- docker-compose-image.yml
- docker-compose-text.yml
- docker-compose-transformers.yml
- docker-compose.yml
- docs/installation.md
- docs/samples/python/streamlit/Dockerfile
- e2e-tests/resources/demo.txt
- e2e-tests/resources/demo_anonymized.txt
- presidio-analyzer/Dockerfile.dev
- presidio-analyzer/pyproject.toml
- presidio-anonymizer/pyproject.toml
- presidio-cli/README.md
- presidio-cli/pyproject.toml
- presidio-image-redactor/Dockerfile
- presidio-image-redactor/Dockerfile.dev
- presidio-image-redactor/pyproject.toml
- presidio-structured/pyproject.toml
1. Python 3.8 EOL date is 2024-10-07. Removed 3.8 and added 3.12
2. removed obsolete `version` parameter from docker-compose
Fixes issue #1473 
3. Fixed failing e2e test (demo website text validation, also updated the demo website's text)
> Removed python 3.8 support (EOL) and added 3.12

- e2e-tests/tests/test_analyzer.py
- presidio-analyzer/app.py
- presidio-analyzer/presidio_analyzer/analyzer_request.py
Add support for allow_list, allow_list_match, regex_flags in REST API
This PR fixes issue [#1470 ](https://github.com/microsoft/presidio/issues/1470)
> Add support for allow_list, allow_list_match, regex_flags in REST API

- docs/analyzer/nlp_engines/transformers.md
- presidio-analyzer/presidio_analyzer/conf/transformers.yaml
Adding a note to direct the user to the classes the model can output on Huggingface
> Add a link to model classes to simplify configuration

- presidio-analyzer/presidio_analyzer/pattern_recognizer.py
The microseconds were output incorrectly before (missing leading zeros). Also, `seconds` was used instead of `total_seconds` (should be irrelevant in practice, though).
> Fix regex match_time output

- presidio-analyzer/pyproject.toml
- pyproject.toml
Puts restriction on installing spacy 3.7.0
This PR fixes issue https://github.com/microsoft/presidio/issues/1487
> Restricting spacy.cli for version 3.7.0

- docs/samples/index.md
- docs/samples/python/gliner.md
- mkdocs.yml
- presidio-analyzer/presidio_analyzer/predefined_recognizers/__init__.py
- presidio-analyzer/presidio_analyzer/predefined_recognizers/gliner_recognizer.py
- presidio-analyzer/pyproject.toml
- presidio-analyzer/tests/test_gliner_recognizer.py
Integrating GLiNER as an `EntityRecognizer`
> example GLiNER integration

- .github/workflows/defender-for-devops.yml
Upgradel codeql to v3:
https://github.blog/changelog/2025-01-10-code-scanning-codeql-action-v2-is-now-deprecated/
> Upgrade codeql

- CHANGELOG.md
- presidio-image-redactor/presidio_image_redactor/dicom_image_pii_verify_engine.py
This PR corrects the type annotation for the `ocr_bboxes` return value in the `verify_dicom_instance` function. The original annotation indicated that ocr_bboxes would be of type dict, but the actual output is a list. Therefore, this PR updates the return type annotation to reflect the correct type of ocr_bboxes as a list.
This PR fixes issue #1548
> Fix return type annotation of verify_dicom_instance function

- presidio-analyzer/presidio_analyzer/nlp_engine/ner_model_configuration.py
- presidio-analyzer/tests/test_nlp_engine_provider.py
Following [this](https://stackoverflow.com/questions/79549787/why-does-presidio-with-spacy-nlp-engine-not-recognize-organizations-and-pesel-wh) issue, drop LABELS_TO_IGNORE default list as it is defined in the default, now used, analyzer configuration
> Don't set a default for LABELS_TO_IGNORE if not specified

- presidio-analyzer/pyproject.toml
transformers project extension is failing due to missing library accelerate
On CI:
https://dev.azure.com/csedevil/Presidio/_build/results?buildId=16960&view=logs&jobId=c95b3c98-5406-5374-cc38-efae5747f3c6&j=c159508c-3a29-50e1-f978-bea95db34528&t=673971d3-9f65-5b91-5977-6c3f5fbb7816
> [Build failure] Add accelerate missing dependency

- presidio-analyzer/presidio_analyzer/nlp_engine/spacy_nlp_engine.py
- presidio-analyzer/tests/test_spacy_nlp_engine.py
- presidio-analyzer/tests/test_stanza_nlp_engine.py
Fixing issue #1574 where as_tuples=True would not work.
Added support for input of type `List[Tuple[str, object]]` where the user might want to add additional context/metatada to the list of texts to process, and get them together with the processed text.
Also fixed an issue with test_stanza_nlp_engine, assuming stanza is always installed.
This PR fixes issue #1574
> fix issue 1574 to support as_tuples

- docs/samples/python/transformers_recognizer/index.md
- presidio-analyzer/tests/test_context_support.py
Description:  
This pull request corrects minor typographical errors in the documentation and test files:
- Fixed a typo in the link reference from [configuruaion.py] to [configuration.py] in the Transformers Recognizer documentation.
- Corrected the spelling of "enhancement" in the context support test docstring.
These changes improve clarity and maintain consistency in the codebase documentation and comments. No functional code changes are included.
> Fix Typos in Documentation and Test Descriptions

- presidio-analyzer/presidio_analyzer/recognizer_registry/recognizers_loader_utils.py
- presidio-analyzer/tests/test_context_support.py
Description:  
This pull request corrects minor typographical errors in the codebase. Specifically, it fixes the spelling of "configuration" in a docstring within `recognizers_loader_utils.py` and changes "recognized" to "recognized" in a comment within `test_context_support.py`. These changes improve code readability and maintain consistency in documentation and comments. No functional code changes are included.
> Fix Typos in Docstrings and Comments

- e2e-tests/README.md
- presidio-analyzer/presidio_analyzer/context_aware_enhancers/lemma_context_aware_enhancer.py
- presidio-analyzer/presidio_analyzer/entity_recognizer.py
- presidio-analyzer/tests/test_context_support.py
🔍 Fixed several spelling mistakes across the codebase:
- `equivilance` → `equivalence`
- `langauge` → `language` 
- `recongnized` → `recognized`
- `preferrably` → `preferably`
>  📝 Fix typos in documentation and code comments

- presidio-cli/README.md
- presidio-image-redactor/README.md
**Description:**
This pull request addresses two minor typographical errors in the project's documentation.
- Corrected "Prerequisities" to "Prerequisites" in `presidio-cli/README.md`.
- Corrected "Unfortunatley" to "Unfortunately" in `presidio-image-redactor/README.md`.
> Fix: Correct typos in documentation

- presidio-analyzer/Dockerfile.stanza
- presidio-analyzer/presidio_analyzer/recognizer_registry/recognizer_registry_provider.py
- presidio-analyzer/tests/conf/test_stanza_without_recognizer.yaml
- presidio-analyzer/tests/test_analyzer_engine_provider.py
Allowing stanza to load even if not in the recognizer registry list, if the nlp engine is stanza, instead of the default spacy recognizer
This PR fixes issue #1641
> Fix for 1641: Load StanzaRecognizer if StanzaNlpEngine is configured

- .github/workflows/defender-for-devops.yml
- docs/faq.md
- docs/structured/index.md
- presidio-analyzer/pyproject.toml
- presidio-anonymizer/pyproject.toml
- presidio-image-redactor/README.md
- presidio-image-redactor/pyproject.toml
- presidio-structured/README.md
- presidio-structured/pyproject.toml
This version includes periodic bug fixes and enhancements. For the full changelog: [CHANGELOG](https://github.com/microsoft/presidio/blob/main/CHANGELOG.md#22359---2025-07-06)
One notable change in behavior is how country-specific recognizers are loaded (PR #1586):
Most country specific recognizers that expect English were put as optional to avoid false positives, and would not work out-of-the-box. Specifically:
- SgFinRecognizer
- AuAbnRecognizer
- AuAcnRecognizer
- AuTfnRecognizer
- AuMedicareRecognizer
- InPanRecognizer
- InAadhaarRecognizer
- InVehicleRegistrationRecognizer
- InPassportRecognizer
- EsNifRecognizer
- InVoterRecognizer
To re-enable them, either change the [default YAML](https://github.com/microsoft/presidio/blob/main/presidio-analyzer/presidio_analyzer/conf/default_recog …
> Version 2.2.359

- presidio-analyzer/presidio_analyzer/predefined_recognizers/country_specific/india/in_aadhaar_recognizer.py
- presidio-analyzer/tests/test_in_aadhaar_recognizer.py
This PR adds regular expressions for the detection of Aadhaar numbers with common contextual separators along with associated test cases. Separators such as '-', ':' and ' ' have already been defined and used to sanitize values, but the recognizer does not have the appropriate regular expressions to identify Aadhaar numbers using such separators.
This PR fixes issue https://github.com/microsoft/presidio/issues/1632
> Issue 1632: Update Indian Aadhaar recognizer to include regex for contextual delimiters

- CHANGELOG.md
- presidio-image-redactor/presidio_image_redactor/dicom_image_redactor_engine.py
- presidio-image-redactor/tests/test_dicom_image_redactor_engine.py
- presidio-image-redactor/tests/test_phi_list.py
Currently make_phi_list only looks at is_name and ignores is_patient so misses metadata words very relevant to PHI
removal. This change makes it use both is_name and is_patient to generate the list of PHI words.
- [X ] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [X ] My code includes unit tests
- [ X] All unit tests and lint checks pass locally
> Fix(DICOM): handle both names and patient

- .github/workflows/ci.yml
- .github/workflows/release.yml
- docker-compose-image.yml
- docker-compose-text.yml
- docker-compose-transformers.yml
- docker-compose.yml
- presidio-analyzer/Dockerfile
- presidio-analyzer/Dockerfile.stanza
- presidio-analyzer/Dockerfile.transformers
- presidio-analyzer/Dockerfile.windows
- presidio-analyzer/dockerignore
- presidio-analyzer/entrypoint.sh
- presidio-anonymizer/Dockerfile
- presidio-anonymizer/Dockerfile.windows
- presidio-anonymizer/dockerignore
- presidio-anonymizer/entrypoint.sh
- presidio-image-redactor/Dockerfile
- presidio-image-redactor/dockerignore
- presidio-image-redactor/entrypoint.sh
A few changes to optimize docker images:
1. Use the right repo for build cache
2. Add dockerignore to remove things we don't need in the images, mainly the tests folder
3. Save layers by running apt install once
4. Use updated syntax for CMD command.
5. Remove NAME build arg
> Optimize Docker Images
