Gopkg.lock
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/handler.go
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/handler_test.go
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/hash_config.go
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/hash_config_test.go
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/mask_config.go
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/mask_config_test.go

add new anonymizer options: hash and mask

add new anonymizer options: hash and mask

---

Gopkg.lock
presidio-analyzer/analyzer/__main__.py
presidio-analyzer/analyzer/field_types/globally/domain.py
presidio-analyzer/analyzer/field_types/globally/email.py
presidio-analyzer/analyzer/field_types/uk/nhs.py
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/anonymizer.go
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/anonymizer_test.go

…lared fields in the anonymizer, which can be overrided by the user if supplied another default within the anonymizer template.

Default transformation

---

presidio-analyzer/analyzer/predefined_recognizers/spacy_recognizer.py
presidio-analyzer/analyzer/predefined_recognizers/uk_nhs_recognizer.py
presidio-analyzer/tests/__init__.py
presidio-analyzer/tests/assertions.py
presidio-analyzer/tests/test_analyzer_engine.py
presidio-analyzer/tests/test_credit_card_recognizer.py
presidio-analyzer/tests/test_crypto_recognizer.py
presidio-analyzer/tests/test_domain_recognizer.py
presidio-analyzer/tests/test_email_recognizer.py
presidio-analyzer/tests/test_entity_recognizer.py
presidio-analyzer/tests/test_iban_recognizer.py
presidio-analyzer/tests/test_ip_recognizer.py
presidio-analyzer/tests/test_pattern.py
presidio-analyzer/tests/test_pattern_recognizer.py
presidio-analyzer/tests/test_recognizer_registry.py
presidio-analyzer/tests/test_spacy_recognizer.py
presidio-analyzer/tests/test_uk_nhs_recognizer.py
presidio-analyzer/tests/test_us_bank_recognizer.py
presidio-analyzer/tests/test_us_driver_license_recognizer.py
presidio-analyzer/tests/test_us_itin_recognizer.py
presidio-analyzer/tests/test_us_passport_recognizer.py
presidio-analyzer/tests/test_us_phone_recognizer.py
presidio-analyzer/tests/test_us_ssn_recognizer.py

@omri374 @eladiw @itye-msft - This PR is not urgent.

Fix Bug #604 - Refactor test assertions + some pylint fixes

---

Dockerfile.python.deps
Makefile
charts/presidio/values.yaml

task 875
On push release, also push to mcr, to make the image public

Add public path to makefile

---

presidio-analyzer/analyzer/entity_recognizer.py
presidio-analyzer/analyzer/predefined_recognizers/us_driver_license_recognizer.py
presidio-analyzer/tests/test_analyzer_engine.py
presidio-analyzer/tests/test_us_driver_license_recognizer.py

Amended us driver license regexes to be more specific
Minor refactor to context calculation
added a test with the demo text

Small changes to US_DRIVER_LICENSE regex to be more specific

---

build.sh
docs/install.md

Minor doc clarifications for docker process

Clarified local docker build process and added build.sh script

---

CONTRIBUTING.md
README.MD
docs/custom_fields.md
docs/deploy.md
docs/development.md
docs/index.md

Rearranged stuff, moved the grpc stuff to the genproto repo (see PR there). Emphasized what's optional and what's not

Improve contribution documentation

---

presidio-analyzer/analyzer/predefined_recognizers/crypto_recognizer.py
presidio-analyzer/tests/test_crypto_recognizer.py

Fix crypto_recognizer throws an exception #241

---

build.sh
docs/deploy.md

Update build.sh script with relevant configuration per container service.
This PR will resolve issue #239

Update build.sh with configuration per service

---

build.sh

fixing parentheses in build.sh

---

docs/development.md

Fixed broken links on documentation

Fixed links

---

presidio-analyzer/tests/assertions.py
presidio-analyzer/tests/test_assertions.py

Add tests verifying correct behavior.

Fix range handling in analyzer test util function.

---

docs/tutorial_analyzer.md

https://github.com/microsoft/presidio/issues/332

fix broken link

---

README.MD
docs/custom_fields.md
docs/developing_recognizers.md
docs/development.md
docs/tutorial_analyzer.md
docs/tutorial_connector.md
pipelines/CI-presidio.yaml
presidio-api/cmd/presidio-api/docs/readme.md

This PR proposes minor documentation updates - a bit of refactoring, spelling and adding notes about the suporting repos (research and genproto)

Documentation Minor Updates

---

azure-pipelines.yml
presidio-analyzer/presidio_analyzer/analyzer_engine.py
presidio-analyzer/pylintrc
presidio-analyzer/setup.cfg
presidio-anonymizer/Pipfile
presidio-anonymizer/Pipfile.lock
presidio-anonymizer/presidio_anonymizer/__init__.py
presidio-anonymizer/presidio_anonymizer/presidio_anonymizer.py
presidio-anonymizer/setup.cfg
presidio-anonymizer/setup.py
presidio-anonymizer/tests/__init__.py
presidio-anonymizer/tests/test_presidio_anonymizer.py

Add template for the anonymizer.

2608 - cookiecutter for anonymizer.

---

presidio-anonymizer/presidio_anonymizer/__init__.py
presidio-anonymizer/presidio_anonymizer/presidio_anonymizer.py
presidio-anonymizer/tests/test_presidio_anonymizer.py

Create anonymize method stub with flask

Create anonymize method stub with flask.

---

.gitignore
azure-pipelines.yml

Disable VERSION validation during V2 development

disable VERSION validation

---

azure-pipelines.yml

fix errors from docker compose on unset vars during PR validation.
also fix names and remove excessive branch name

Bug - Errors in pipeline

---

functional-tests/common/methods.py
functional-tests/tests/test_analyzer.py
presidio-analyzer/README.MD
presidio-analyzer/app.py

Added an endpoint to return the supported entities of Analyzer.
+ integration tests

Analyzer: get supported entities

---

azure-pipelines.yml
docs/deployment-samples/deploy-to-app-service.md
presidio-anonymizer/app.py

This PR adds:
* split pipeline to stages: build&test and deploy
* deploy to app service in B/G deployment: create slot, deploy to slot, run smoke test on slot, swap slot if successful, delete slot (always).
* use variable group for pipeline instead of singular variables.

CI - Deploy to dev environment

---

functional-tests/tests/test_analyzer.py
presidio-analyzer/app.py
presidio-analyzer/presidio_analyzer/analysis_explanation.py
presidio-analyzer/presidio_analyzer/analyzer_engine.py
presidio-analyzer/presidio_analyzer/recognizer_result.py

analyze/ to return json, not json string

---

docs/deployment-samples/deploy-to-app-service.md
docs/deployment-samples/presidio-app-service.json
docs/deployment-samples/presidio-services.json
presidio-analyzer/README.MD
presidio-analyzer/deploytoazure.json
presidio-anonymizer/README.MD
presidio-anonymizer/deploytoazure.json

This PR fixes ARM template for App service to have:
* ARR affinity turned off
* Always on = true
Additionally, ARM template links have been changed to V2 branch.

ARM Template links

---

docs/samples/deployments/app-service/deploy-to-app-service.md
docs/samples/deployments/app-service/presidio-services.json
presidio-analyzer/README.MD
presidio-analyzer/deploytoazure.json
presidio-anonymizer/README.MD
presidio-anonymizer/deploytoazure.json

deploy to azure button stopped functioning. templates links had to change

Bug - template were moved to docs 

---

functional-tests/tests/test_anonymizer.py
presidio-anonymizer/app.py

Move error handling into handlers.
return json from API

return json response from API

---

Dockerfile.python.deps
docs/deploy.md
docs/overview.md
pipelines/templates/build-python-template.yaml
pipelines/templates/build-test-publish.yaml
presidio-analyzer/Pipfile
presidio-analyzer/Pipfile.lock
presidio-analyzer/presidio_analyzer/pattern_recognizer.py
presidio-analyzer/presidio_analyzer/predefined_recognizers/iban_recognizer.py

Fix showstopper bug on V1 before migrating to V2

V1: Removed pyre2 dependency

---

functional-tests/common/methods.py
functional-tests/tests/test_anonymizer.py
presidio-anonymizer/app.py

API improvements - fix code review comments

fix code review comments.

---

presidio-image-anonymizer/Pipfile
presidio-image-anonymizer/Pipfile.lock

V2 image anonymizer pipenv

---

presidio-image-anonymizer/Pipfile
presidio-image-anonymizer/Pipfile.lock
presidio-image-anonymizer/app.py

add stub for image anonymizer stub for REST API server

V2 image anonymizer flask stub

---

azure-pipelines-ci.yml

Batch CI pipelines to avoid parallel executions  

---

presidio-analyzer/setup.py

Added missing pyyaml dependency to setup.py

added pyyaml to setup.py

---

presidio-analyzer/setup.py
presidio-anonymizer/setup.py
presidio-image-anonymizer/setup.py

[ADO-2802]
Set README.MD content as package description for all Presidio packages.

Add README as package description

---

presidio-image-anonymizer/Pipfile
presidio-image-anonymizer/Pipfile.lock
presidio-image-anonymizer/setup.py

Fix imports for image anonymizer

image anonymizer v2 imports

---

azure-pipelines-ci.yml

Don't delete staging slots on CI deployment

---

.pipelines/templates/release.yml

Tag containers with v2-latest 

---

presidio-analyzer/tests/test_aba_routing_recognizer.py
presidio-analyzer/tests/test_analyzer_engine.py
presidio-analyzer/tests/test_context_support.py
presidio-analyzer/tests/test_credit_card_recognizer.py
presidio-analyzer/tests/test_crypto_recognizer.py
presidio-analyzer/tests/test_domain_recognizer.py
presidio-analyzer/tests/test_email_recognizer.py
presidio-analyzer/tests/test_entity_recognizer.py
presidio-analyzer/tests/test_es_nif_recognizer.py
presidio-analyzer/tests/test_iban_recognizer.py
presidio-analyzer/tests/test_ip_recognizer.py
presidio-analyzer/tests/test_nlp_engine_provider.py
presidio-analyzer/tests/test_pattern.py
presidio-analyzer/tests/test_pattern_recognizer.py
presidio-analyzer/tests/test_recognizer_registry.py
presidio-analyzer/tests/test_sg_fin_recognizer.py
presidio-analyzer/tests/test_spacy_recognizer.py
presidio-analyzer/tests/test_stanza_recognizer.py
presidio-analyzer/tests/test_uk_nhs_recognizer.py
presidio-analyzer/tests/test_us_bank_recognizer.py
presidio-analyzer/tests/test_us_driver_license_recognizer.py
presidio-analyzer/tests/test_us_itin_recognizer.py
presidio-analyzer/tests/test_us_passport_recognizer.py
presidio-analyzer/tests/test_us_phone_recognizer.py
presidio-analyzer/tests/test_us_ssn_recognizer.py
presidio-anonymizer/tests/anonymizers/test_hash.py
presidio-anonymizer/tests/anonymizers/test_mask.py
presidio-anonymizer/tests/anonymizers/test_redact.py
presidio-anonymizer/tests/anonymizers/test_replace.py

Simple name refactoring to unify all test names of analyzer and anonymizer

refactor test names based on namng convention

---

presidio-image-anonymizer/Dockerfile

update image anonymizer - install spacy and tesseract

Image anonymizer dockerafile with spacy and tesseract

---

presidio-image-anonymizer/app.py

Fix import since it blocks the docker from running

fix imports

---

presidio-image-anonymizer/presidio_image_anonymizer/entities/api_request_convertor.py

fix import

---

.github/CODEOWNERS
.gitignore
.pipelines/templates/lint-build-test.yml

Remove version validation from pipeline and update codeowners

---

docs/development.md
docs/samples/docker/PresidioAnalyzer.postman_collection.json
docs/samples/docker/PresidioAnonymizer.postman_collection.json
docs/samples/docker/index.md
docs/samples/index.md
docs/samples/python/index.md

1. Add postman collection with REST API usage samples
2. Samples docs minor update

Add usage samples

---

mkdocs.yml

Adds nav for API documentation html

Add REST API reference link to Mkdocs

---

README.MD

1. Created a V1 branch
2. Added some documentation on how to use V1 and how to migrate to V2.

V1 README update (deprecation notice)

---

presidio-analyzer/README.MD

delete analyzer docs links

---

docs/analyzer/index.md
docs/anonymizer/adding_anonymizers.md
docs/anonymizer/index.md
mkdocs.yml

Add anonymizer docs and how to add new anonymizer.

add anonymizer docs

---

.pipelines/templates/release.yml

fix issue with release pipeline

fix release pipeline

---

.pipelines/templates/release-docs.yml

Update release-docs.yml for Azure Pipelines

---

docs/samples/docker/index.md

Old url points to navalev's repo
New url points to microsoft's repo

Fixed installation guide url

---

presidio-image-redactor/Pipfile
presidio-image-redactor/Pipfile.lock

This PR resolves the build issues in PR https://github.com/microsoft/presidio/pull/622 image-redactor build in python 3.6 and 3.7

Image Redactor bump pillow from 8.1.0 to 8.1.1 

---

presidio-image-redactor/presidio_image_redactor/image_analyzer_engine.py

Hopefully this should fix #645.

image redactor: initialize AnalyzerEngine instance only once

---

docs/requirements-docs.txt
mkdocs.yml

Following
https://github.com/squidfunk/mkdocs-material/issues/2511

Upgrade mkdocs-material to latest

---

docs/samples/deployments/data-factory/presidio-data-factory-template-gallery.md
docs/samples/deployments/data-factory/presidio-data-factory.md

* fix link to template in docs/samples/deployments/data-factory/presidio-data-factory-template-gallery.md
* added "about this solution template" section to both ADF samples to be consistent with the template gallery sample.

ADF templates docs

---

.pipelines/templates/release.yml

Add a step for tagging git with Presidio version.

Add Git tag on release

---

presidio-analyzer/presidio_analyzer/nlp_engine/spacy_nlp_engine.py

Lemmatization (leveraged by the context words detection mechanism), requires the spacy tagger to be active in spaCy 3. This PR introduces the tagger step into spacy's pipeline.

Adding tagger to the spaCy model pipeline

---

presidio-image-redactor/Pipfile
presidio-image-redactor/Pipfile.lock
presidio-image-redactor/setup.py

As a prerequisite to https://github.com/microsoft/presidio/pull/646, this adds the new dependency.

Add matplotlib to image-redactor

---

CONTRIBUTING.md
presidio-analyzer/presidio_analyzer/predefined_recognizers/__init__.py
presidio-analyzer/presidio_analyzer/predefined_recognizers/date_recognizer.py
presidio-analyzer/presidio_analyzer/recognizer_registry/recognizer_registry.py
presidio-analyzer/tests/test_date_recognizer.py
presidio-analyzer/tests/test_recognizer_registry.py

Add a new regex based recognizer to detect dates in format such as 2021/05/21, 21-MAY-2021, 21.5.2021 

Date recognizer

---

presidio-analyzer/presidio_analyzer/nlp_engine/stanza_nlp_engine.py
presidio-analyzer/presidio_analyzer/predefined_recognizers/stanza_recognizer.py
presidio-analyzer/presidio_analyzer/recognizer_registry/recognizer_registry.py

the Spacy-Stanza interface had changed in spaCy 3. This PR proposes:
1. The fix to the spacy-stanza interface.
2. Bug fix on getting the right recognizer given the nlp engine (`SpacyRecognizer` for `SpancyNlpEngine` and `StanzaRecognizer` for `StanzaNlpEngine`)
3. Bug fix in the decision process string for Stanza

Updated call to stanza via spacy-stanza

---

presidio-image-redactor/Pipfile
presidio-image-redactor/Pipfile.lock

Updated `pillow` and `presidio-analyzer` versions on presidio-image-redactor due to a security issue.

Updates to pillow version and presidio-analyzer

---

docs/community.md
mkdocs.yml

Added a doc with list of OSS leveraging Presidio

Add list of OSS tools leveraging Presidio

---

.pipelines/templates/deploy-stage.yml
.pipelines/templates/release.yml
docs/requirements-docs.txt

following https://developercommunity.visualstudio.com/t/pipeline-variable-incorrectly-inserts-single-quote/375679#T-N394968
This should fix the release issue where a single quote is added to the parsed version

remove set -x from setvariable tasks

---

.github/workflows/codeql-analysis.yml
.github/workflows/stale.yml

This PR adds GH action that scans the code for vulenrabilities using codeQL
issue #872 
- [* ] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [* ] I have signed the CLA

Add GH code scanning with codeQL

---

README.MD

Update README with ossf badge
- [v ] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [ v] I have signed the CLA
- [ v] My PR contains documentation updates / additions if required

Update README with OSSF best practices badge

---

.pipelines/templates/build-analyzer.yml
.pipelines/templates/build-anonymizer.yml
.pipelines/templates/build-image-redactor.yml
docs/development.md

This PR fixes the CI build by removing --sequential option from pipenv sync commnad.
Remove --sequential option from pipenv sync commnad and docs.
This PR fixes issue #920
- [v] I have reviewed the [contribution guidelines](https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md)
- [v] I have signed the CLA
- [v] All unit tests and lint checks pass locally
- [v] My PR contains documentation updates / additions if required

Remove --sequential from pipenv sync

---

presidio-analyzer/presidio_analyzer/nlp_engine/transformers_nlp_engine.py

hotfix for #911. Tests to follow as part of #912

Fix for misalignment between transfrormers and spacy

---

CHANGELOG.md
presidio-image-redactor/presidio_image_redactor/image_pii_verify_engine.py

Updating the ImagePiiVerifyEngine class to enable passing of a non-default analyzer engine into it. This is needed for cases where a custom recognizer is used.

Update to ImagePiiVerifyEngine class

---

README.MD
docs/samples/index.md
docs/samples/python/csv_sample_data/sample_data.csv
docs/samples/python/example_csv.py

Sample for anaylzing and anonymizing csv file - using batch analyzer

Sample - analyze and anonymize csv file 

---

docs/samples/python/flair_recognizer.py

Flair recognier sample - fix access to start  end positions

---

e2e-tests/common/methods.py
e2e-tests/tests/test_image_redactor.py
presidio-image-redactor/app.py
presidio-image-redactor/tests/test_dicom_image_redactor_engine.py

Support sending image as encoded byte array, to align with `input` based web application components.

Image Redactor - REST API to support web applications payload

---

docs/api-docs/api-docs.yml

Define `anonymizers` attribute of the Anonymize API request as a map
Showing as such in redoc:
This PR fixes issue #1016

Fix Anonymize API documentation

---

.pipelines/templates/build-and-push-containers.yml
.pipelines/templates/release.yml
azure-pipelines-ci.yml

Temporarily don't push and deploy to dev and prod

Skip pushing images and deploying services

---

docs/supported_entities.md

Fixed the names of a couple of entity types in the docs
There is no issue, I went straight to the PR

Fix name of a couple of entity types in the docs

---

.pipelines/templates/build-and-push-containers.yml
azure-pipelines-ci.yml

Onboard to dstoolkit ACR by matching the generic container registry service connection (vs Azure)

Change ACR instance

---

presidio-analyzer/presidio_analyzer/recognizer_registry/recognizer_registry.py

Update the type check to be consistent.
This PR fixes issue #1174

update type check

---

README.MD
docs/index.md

Added a link to a survey:
Please help us improve by taking [this short anonymous survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR9LagCGNW01LpMix2pnFWFJUQjJDTVkwSlJYRkFPSUNNVlVRRVRWVDVNSy4u).
This is how it looks like on the readme:

Added a survey link

---

docs/anonymizer/adding_operators.md

Very mino typo fix - linter removed trailing spaces too.

minor typo fix

---

docs/tutorial/06_context.md

Fixed the tutorial for context aware enhancer (#1265)
This PR fixes issue #1265

bug fix in tutorial (#1265)

---

presidio-analyzer/presidio_analyzer/predefined_recognizers/crypto_recognizer.py
presidio-analyzer/tests/test_crypto_recognizer.py

Using [base58](https://pypi.org/project/base58/) as reference
@miltonsim FYI
This PR fixes issue #1376

Fix OverflowError in crypto_recognizer

---

README.MD

Added presidio structured downloads to readme

---

docs/installation.md

Another port documentation fix In addition to https://github.com/microsoft/presidio/pull/1375 
This PR fixes issue #1363

Fix ports in docs

---

CHANGELOG.md
docs/samples/python/transformers_recognizer/transformer_recognizer.py

Fix the entity filtering of the transformer_recognizer.py analzye function

---

docs/samples/python/transformers_recognizer/transformer_recognizer.py

Added missing ":" after if condition check

Typo fix added missing ":" after if condition

---

presidio-analyzer/presidio_analyzer/analyzer_engine_provider.py
presidio-analyzer/presidio_analyzer/nlp_engine/nlp_engine_provider.py

closing handles

---

.pipelines/templates/build-and-push-containers.yml
azure-pipelines-ci.yml
azure-pipelines.yml
docker-compose.yml

Use ACR service connection when pushing containers

Use ACR service connection when pushing containers

---

docs/api/analyzer_python.md
mkdocs.yml
presidio-analyzer/presidio_analyzer/context_aware_enhancers/__init__.py

Removing unnecessary sections in the python api docs
**No code changes**
This PR fixes issue #1502

minor updates to the mkdocstrings config

---

presidio-anonymizer/pyproject.toml

Remove the azure-core dep as it's unused
This PR fixes issue #1514

remove azure-core dependency from anonymizer

---

presidio-image-redactor/pyproject.toml
presidio-structured/pyproject.toml

Fix python 3.9 Builds

---

CHANGELOG.md
presidio-analyzer/pyproject.toml
presidio-anonymizer/pyproject.toml
presidio-cli/pyproject.toml
presidio-image-redactor/pyproject.toml
presidio-structured/pyproject.toml

Version 2.2.358

---

presidio-analyzer/presidio_analyzer/predefined_recognizers/in_pan_recognizer.py
presidio-analyzer/tests/test_in_pan_recognizer.py

Lowered the initial score for IN_PAN due to many false positives

Updated initial scores in IN_PAN

---

.github/dependabot.yml

dependabot.yaml now needs to be explicitly committed

Restore dependabot scanning

---

presidio-analyzer/pyproject.toml

Bump phonenumbers version
This PR fixes issue #1578

Bump phonenumbers version

---

presidio-anonymizer/presidio_anonymizer/operators/keep.py
presidio-anonymizer/presidio_anonymizer/operators/redact.py

Fix minor typos

---

.github/codeql.yml
.github/workflows/codeql-analysis.yml
.github/workflows/defender-for-devops.yml

Reverts microsoft/presidio#1594

Revert "Update codeql-analysis.yml"

---

docs/api-docs/api-docs.yml

Fix typo in api-docs.yml

---

.gitignore

Added `.vs` folder to `.gitignore` to support opening the project in Visual Studio.

Update gitignore for `.vs` folder

---

README.MD
docs/index.md
docs/installation.md

Added links to the discussion on Docker to the readme, docs index and installation docs.

Links to discussion board on Docker prebuilt images

---

.gitignore

Add the "/TestResults" folder (which is created by Visual Studio when running the test) to the `.gitignore` file.

Add the "/TestResults" to .gitignore file

---

presidio-anonymizer/presidio_anonymizer/operators/encrypt.py

Update encrypt.py - Indenting

---

docs/samples/deployments/openai-anonymaztion-and-deanonymaztion-best-practices/src/client_app/requirements.txt
e2e-tests/requirements.txt

Update requests to mitigate https://github.com/advisories/GHSA-9hjg-9r4m-mvj7

Force new requests to mitigate GHSA-9hjg-9r4m-mvj7

---

CHANGELOG.md
presidio-analyzer/pyproject.toml
presidio-anonymizer/pyproject.toml

Release Version 2.2.360 for analyzer and anonymizer

Release Version 2.2.360

---

docs/tutorial/02_regex.md

Fix warning of deprecated escape sequence

Update 02_regex.md, fix warning of deprecated escape sequence

---

docs/samples/python/example_custom_lambda_anonymizer.py
presidio-analyzer/presidio_analyzer/context_aware_enhancers/lemma_context_aware_enhancer.py
presidio-analyzer/presidio_analyzer/nlp_engine/ner_model_configuration.py
presidio-analyzer/presidio_analyzer/nlp_engine/nlp_artifacts.py
presidio-analyzer/presidio_analyzer/nlp_engine/nlp_engine.py
presidio-analyzer/presidio_analyzer/nlp_engine/transformers_nlp_engine.py
presidio-analyzer/presidio_analyzer/pattern_recognizer.py
presidio-analyzer/presidio_analyzer/predefined_recognizers/country_specific/poland/pl_pesel_recognizer.py
presidio-analyzer/presidio_analyzer/predefined_recognizers/country_specific/spain/es_nif_recognizer.py
presidio-analyzer/presidio_analyzer/predefined_recognizers/country_specific/us/aba_routing_recognizer.py
presidio-analyzer/presidio_analyzer/predefined_recognizers/country_specific/us/medical_license_recognizer.py
presidio-analyzer/presidio_analyzer/predefined_recognizers/country_specific/us/us_ssn_recognizer.py
presidio-analyzer/presidio_analyzer/predefined_recognizers/generic/credit_card_recognizer.py
presidio-analyzer/presidio_analyzer/predefined_recognizers/generic/email_recognizer.py
presidio-analyzer/presidio_analyzer/predefined_recognizers/generic/iban_recognizer.py
presidio-analyzer/presidio_analyzer/predefined_recognizers/generic/phone_recognizer.py
presidio-analyzer/presidio_analyzer/predefined_recognizers/nlp_engine_recognizers/spacy_recognizer.py
presidio-analyzer/presidio_analyzer/predefined_recognizers/nlp_engine_recognizers/stanza_recognizer.py
presidio-analyzer/presidio_analyzer/predefined_recognizers/nlp_engine_recognizers/transformers_recognizer.py
presidio-analyzer/presidio_analyzer/predefined_recognizers/third_party/azure_ai_language.py
presidio-analyzer/presidio_analyzer/remote_recognizer.py
presidio-analyzer/tests/__init__.py
presidio-analyzer/tests/test_analyzer_engine.py
presidio-image-redactor/tests/conftest.py
pyproject.toml

CodeQL warns about deprecated syntax when using the `noqa` comments. This supposed to fix that and remove a bunch of "security" warnings, but could only be confirmed after this arrives at the main branch.

Update noqa syntax
